"""
Lightline module
"""
import enum
import datetime
from os import listdir

from hapycolor import targets
from hapycolor import exceptions
from hapycolor import helpers
from hapycolor.targets import base
from hapycolor.targets import eight_bit_colors
from hapycolor.targets import vim
from hapycolor.targets import pam


class Lightline(base.Target):
    """
    Then, once a palette is fed to the class, a lightline colorscheme is
    generated by pairing the variables to colors defined in the provided
    palette.

    Supported themes:

    - Landscape
    - One
    - Wombat
    - Solarized
    """
    ThemeEnum = enum.Enum("ThemeEnum",
                          [(t.split('.')[0].upper(),
                            "hapycolor/targets/lightline/" + t)
                           for t in listdir("./hapycolor/targets/lightline") if ".vim" in t])

    # The colorscheme's path
    colorscheme_key = "colorscheme"

    # Will be asked during target's configuration
    theme_key = "theme"

    @staticmethod
    def initialize_config():
        colorscheme_path = Lightline.select_colorscheme_path()
        theme = Lightline.select_theme()
        Lightline.save_config({
            Lightline.colorscheme_key: colorscheme_path,
            Lightline.theme_key: str(theme.value)})

    @staticmethod
    def reconfigure():
        try:
            entry = int(input("\nTheme: 1\nLightline's path: 2\nEntry: "))
            if entry not in [1, 2]:
                raise ValueError
        except ValueError:
            print("Wrong input")
            Lightline.reconfigure()

        if entry == 1:
            theme = Lightline.select_theme()
            Lightline.save_config({Lightline.theme_key: str(theme.value)})
        elif entry == 2:
            colorscheme_path = Lightline.select_colorscheme_path()
            entry = {Lightline.colorscheme_key: colorscheme_path}
            Lightline.save_config(entry)

    @staticmethod
    def select_colorscheme_path():
        p = vim.environment.VimEnvironments.find_plugin("lightline.vim")
        file_path = p + "/autoload/lightline/colorscheme/hapycolor.vim"
        return file_path

    @staticmethod
    def select_theme():
        try:
            print("\nSelect a theme:")
            for i, theme in enumerate(Lightline.ThemeEnum):
                print(theme.name + ": (" + str(i) + ")")
            theme_i = int(input("Theme: "))
            if theme_i < 0 or len(Lightline.ThemeEnum) <= theme_i:
                raise ValueError
            return list(Lightline.ThemeEnum)[theme_i]
        except ValueError:
            print("Value must be an integer between 0 and "
                  + str(len(Lightline.ThemeEnum)))
            return Lightline.select_theme()

    @staticmethod
    def is_config_initialized():
        try:
            config = Lightline.load_config()
            return (Lightline.colorscheme_key in config) \
                and (Lightline.theme_key in config)
        except exceptions.InvalidConfigKeyError:
            return False

    @staticmethod
    def compatible_os():
        return [targets.OS.DARWIN, targets.OS.LINUX]

    @staticmethod
    def export(palette, image_path):
        """
        This function extract the targeted colors of the palette and defines
        the color's variables used in the theme's template defined in the
        configuration file.
        """

        theme = Lightline.add_header(image_path)
        theme += Lightline.add_body()
        theme = Lightline.add_colors(theme, palette)

        colorscheme = Lightline.load_config()[Lightline.colorscheme_key]
        with open(colorscheme, 'w') as colorscheme_file:
            colorscheme_file.write('\n'.join(theme))

    @staticmethod
    def add_body():
        theme_path = Lightline.load_config()[Lightline.theme_key]
        body = []
        with open(theme_path, "r") as theme_file:
            body = theme_file.read()
        return body

    @staticmethod
    def add_colors(theme, palette):
        colors = Lightline.classify(palette.colors)

        # Sort by hue and rearrange in the following order:
        # NORMAL, INSERT, REPLACE, VISUAL, FOREGROUND, BACKGROUND
        hsl_colors = [helpers.rgb_to_hsl(c) for c in colors]
        hsl_colors.sort(key=lambda c: c[0])
        hsl_colors = [hsl_colors[1], hsl_colors[0], hsl_colors[3], hsl_colors[2]]
        colors = [helpers.hsl_to_rgb(c) for c in hsl_colors]
        colors.extend([palette.foreground, palette.background])

        modes = ["$NORMAL", "$INSERT", "$REPLACE", "$VISUAL", "$FG", "$BG"]
        for mode, color in zip(modes, colors):
            new_value = "'{}', {}".format(helpers.rgb_to_hex(color),
                                          eight_bit_colors.rgb_to_short(color))
            theme = theme.replace(mode, new_value)
        return theme.split('\n')

    @staticmethod
    def classify(colors):
        def distance(c1, c2):
            """ Evaluates the hue's distance """
            return abs(c1[0] - c2[0])

        k = 4 # There are four modes: Insert, Visual, Normal and Replace
        colors = pam.PAM(colors, k, distance)()

        # Only the medoids of each cluster will used
        return [m for m in colors]

    @staticmethod
    def add_header(image_path):
        now = datetime.datetime.now()
        date = "{}/{}/{} {}:{}:{}.".format(now.day, now.month, now.year,
                                           now.hour, now.minute, now.second)
        return """
" =============================================================================
" Filename: autoload/lightline/colorscheme/hapycolor.vim
" Author: hapycolor
" License: MIT License
" Last Change: {}
" Source image: {}
" =============================================================================
""".format(date, image_path)
